version: "3.9"
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    networks:
      - my-network

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - my-network

  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    networks:
      - my-network